name: dailyfamilymessage
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  path_provider: ^2.1.5
  url_launcher: ^6.2.0

  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.1.3
  shared_preferences: ^2.5.4

  weather_package: 
    path: weather_package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

